NAME = libft.a


SRCS_DIR = srcs
INCLUDES_DIR = includes

SRCS = $(SRCS_DIR)/ft_putchar.c $(SRCS_DIR)/ft_putstr.c \
	$(SRCS_DIR)/ft_strcmp.c $(SRCS_DIR)/ft_strlen.c \
	$(SRCS_DIR)/ft_swap.c

OBJS = $(SRCS:.c=.o)

CC = gcc
CFLAGS = -Wall -Wextra -Werror -I $(INCLUDES_DIR)

all : $(NAME)

$(NAME): $(OBJS)
	@ar rcs $(NAME) $(OBJS)

%.o: %.c
	@$(CC) $(CFLAGS) -c $< -o $@
clean:
	@rm -f $(OBJS)

fclean: clean
	@rm -f $(NAME)

re: fclean all



